language: ruby
rvm:
  - 1.9.3
  - 2.1.5
script:
  - git clone https://github.com/puppetlabs/puppetlabs-stdlib.git ../stdlib
  - "bundle exec rake lint"
  - "bundle exec rake spec SPEC_OPTS='--format documentation'"
env:
  - PUPPET_VERSION="~> 3.0.0"
  - PUPPET_VERSION="~> 3.1.0"
  - PUPPET_VERSION="~> 3.2.0"
  - PUPPET_VERSION="~> 3.3.0"
  - PUPPET_VERSION="~> 3.4.0"
  - PUPPET_VERSION="~> 4.0.0"
  - PUPPET_VERSION="~> 4.1.0"
  - PUPPET_VERSION="~> 4.2.3"
  - PUPPET_VERSION="~> 4.4.2"
  - PUPPET_VERSION="~> 4.5.3"
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.7.0"
    - rvm: ruby-head
      env: PUPPET_GEM_VERSION="~> 2.7.0"
gemfile: .gemfile
notifications:
  email:
    - schrepfler@gmail.com
